name: create a comment on new issues

on: 
  issues:
    types: [opened]

jobs:
  comment-with-action:
    runs-on: ubuntu-latest
    steps:
      # - name: comment with action
      #   uses: actions/github-script@v3
      #   with:
      #     github-token: ${{ secrets.GITHUB_TOKEN }}
      #     script: |
      #       github.issues.createComment({
      #         issue_number: context.issue.number,
      #         owner: context.repo.owner,
      #         repo: context.repo.repo,
      #         body: 'Thanks for opening this issue!'
      #       })
        - name: "dump github context"
          run: echo '${{ toJson(github.event) }}' | jq
          shell: bash
        - name: Create comment
          uses: peter-evans/create-or-update-comment@v1
          with:
            token: ${{ secrets.GITHUB_TOKEN }}
            repository: ${{ github.repository }}
            issue-number: ${{ github.event.issue.number }}
            body: |
              Thanks for opening this issue!
              This is a comment created by a GitHub Action.
              The body of the comment is in markdown.
            reactions: '+1'
            repo-token: ${{ secrets.GITHUB_TOKEN }}